guest_list = ['Dwayne "The Rock" Johnson', 'Doctor Phil', 'Albert Camus', 'Mikhail Gorbachev',]
dead = guest_list.pop(2)
print(f"{dead} is unable to attend as he is dead.")
guest_list.insert(2, 'Psy')
print(f"Greetings {guest_list[0]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[1]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[2]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[3]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print('A new, larger albeit uglier dinner table has been found! New guests will be invited shortly.')
guest_list.insert(0, 'Larry David')
guest_list.insert(3, 'Britney Spears')
guest_list.append('Cardi B')
print(f"Greetings {guest_list[0]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[1]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[2]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[3]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[4]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[5]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
print(f"Greetings {guest_list[6]}, you are being formally invited to a dinner hosted by myself. RSVP at the return address promptly.")
